# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ceb1eb0d5b9b58d0f8a8af9b97e2031db70d0902202e1f56330680975ba0d3ce4b2e7b9aa90f7d59a76b23db22cee367d218fd7878fc7ea8f890e201b2e4c05

test:
  secret_key_base: 28d48141015760afbc56789e4d097d6183088463029dc10b5314bf9ed7a323ec9fdb98a2efca00ef465847005b58b17a5db7efc1c5e313287b12e6173a93c11e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
